@startuml USDs Yield Generation Flow

title USDs Yield Generation Flow
actor User
participant Vault
participant CollateralManager
participant Strategy
participant YieldReserve
participant Dripper
box "External Contracts" #LightBlue
    participant Collateral
    participant "Yield Earning Strategies" as YieldEarningStrategies
end box

group Allocate
    User -> Vault: allocate(collateral, strategy, amount)
    group validate allocation
        Vault -> CollateralManager: validateAllocation(collateral, strategy, amount)
        CollateralManager --> Vault: Boolean (true/false)
    end
    Vault -> Collateral: forceApprove(strategy, amount)
    Vault -> Strategy: deposit(collateral, amount)
    note over Strategy: Validate support for collateral
    Strategy -> Collateral: safeTransferFrom(vault, strategy, amount)
    Collateral --> Strategy: Collateral amount
    Strategy -> YieldEarningStrategies: Deposit collateral for earning yield
end

group Harvest
    User -> Strategy: collectReward() / checkRewardEarned()
    Strategy --> User: Harvest Incentive
    Strategy --> YieldReserve: Harvest Amount
end

group Yield purchase using USDs
    User -> YieldReserve: swap(srcToken, dstToken, amountIn, minAmountOut)
    YieldReserve --> User: dstToken
    YieldReserve -> Dripper: addUSDs(rebaseAmt)
    note over YieldReserve, Dripper: USDs for rebase
end

@enduml
