@startuml USDs Yield Generation Flow

title USDs Yield Generation Flow
actor User
participant Vault
participant CollateralManager
participant Strategy
participant YieldReserve
participant Dripper
box "External Contracts" #LightBlue
    participant Collateral
    participant "Yield Earning Strategies" as YieldEarningStrategies
end box

group Allocate
    User -> Vault: allocate(collateral, strategy, amount)
    Vault -> CollateralManager: validateAllocation(collateral, strategy, amount)
    CollateralManager -> Vault: Boolean (true/false)
    note over Vault: Validate allocation
    Vault -> Collateral: forceApprove(strategy, amount)
    Vault -> Strategy: deposit(collateral, amount)
    note over Strategy: Validate support for collateral
    Strategy -> Collateral: safeTransferFrom(vault, strategy, amount)
    Vault --> Strategy: Collateral (amount)
    Strategy -> YieldEarningStrategies: Deposit collateral in yeild earning strategies
    Strategy --> YieldEarningStrategies: Collateral (amount)
end

group Harvest
    User -> Strategy: collectReward() / checkRewardEarned()
    Strategy --> User: Harvest Incentive
    YieldEarningStrategies --> Strategy: Harvest Amount
    Strategy --> YieldReserve: Harvest Amount
end

group Yield purchase using USDs
    User -> YieldReserve: swap(srcToken, dstToken, amountIn, minAmountOut)
    User --> YieldReserve: srcToken (amountIn)
    YieldReserve --> User: dstToken
    YieldReserve -> Dripper: addUSDs(rebaseAmt)
    YieldReserve --> Dripper: USDs (rebaseAmt)
    note over YieldReserve, Dripper: USDs for rebase
end

@enduml
